# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Vite app to Azure Web App - test-medium

# Run the workflow whenever a change is pushed into the main branch
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  # Example environment variables for Vite
  VITE_APP_NAME: test-medium

jobs:
  # Build the application for production.
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Cache Node.js dependencies for faster builds
      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Set up Node.js version
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      # Install dependencies, build, and test
      - name: Install dependencies and build
        run: |
          npm install
          npm run build
        env:
          VITE_APP_NAME: test-medium

      # Upload artifact for deployment job
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: vite-app
          path: dist # Ensure the `dist` folder is generated by Vite

  # Deploy the application to Azure
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      # Download the artifact from the build job
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: vite-app

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: test-medium
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: dist
